security:
    encoders:
        App\Entity\Utilisateurs:
            algorithm: sha512
        App\Entity\Magasins:
            algorithm: sha512
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateurs
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            guard:
                authenticators:
                    - App\Security\UtilisateursAuthenticator
            logout:
                path: app_logout
                target: app_login
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/validation$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }